# Generated by Django 3.1.3 on 2020-12-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='mins_ago',
            field=models.IntegerField(default=1440),
        ),
        migrations.AlterField(
            model_name='headline',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
