# Generated by Django 3.2.4 on 2021-06-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_headline_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='leaning',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='headline',
            name='time_ago_str',
            field=models.TextField(null=True),
        ),
    ]
