# Generated by Django 3.2.4 on 2021-06-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210612_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='img',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
